name: 获取 apt 源列表
on:
  workflow_dispatch:

jobs:
  Get:
    runs-on: ubuntu-24.04
    steps:
      - name: 新建文件夹
        run: mkdir sources
      - name: 获取 apt 源列表
        run: sudo cp /etc/apt/sources.list.d/ubuntu.sources sources/ubuntu.sources
      - name: 打包上传
        uses: actions/upload-artifact@v4
        with:
          path: sources