name: 获取 apt 源列表
on:
  workflow_dispatch:

jobs:
  Get:
    runs-on: ubuntu-24.04
    steps:
      - name: 获取 apt 源列表
        run: sudo cp /etc/apt/sources.list sources/sources.list
      - name: 打包上传
        uses: actions/upload-artifact@v4
        with:
          path: sources